[package]
name = "ace411_sudoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sudoku = "0.7.0"
anyhow = "1.0.44"
serialport = "4.0.1"
colored = "2.0.0"

