name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install mingw-w64 Linker
      run: sudo apt-get install mingw-w64 libudev-dev pkg-config
    - name: Add Windows Target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build Windows
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: Build Linux
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
      
  release:
    needs: build
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            target/x86_64-pc-windows-gnu/release/ace411_sudoku.exe
            target/x86_64-unknown-linux-gnu/release/ace411_sudoku
